"""
Integration tests for the LLM router.

These tests verify the complete interaction between:
    Router -> Primary provider -> Retry -> Fallback provider

No real Groq/Gemini API calls are made. Fake providers are used so
the tests are deterministic and safe for CI.
"""

import pytest

from engine.llm.base import (
    LLMConfigError,
    LLMExplanation,
    LLMOutputError,
    LLMTransientError,
)
from engine.llm.router import (
    LLMAllProvidersFailedError,
    explain,
)


SAMPLE_AI_INPUT = {
    "finding_id": "F-INTEGRATION-001",
    "audit_run_id": "RUN-INTEGRATION-001",
    "control_id": "SCREENING_001",
    "customer_id": "CUST-001",
    "severity": "HIGH",
    "assessment_status": "FAIL",
    "expected": "Screening must be CLEAR.",
    "actual": "Screening was PENDING.",
    "evidence": {
        "customer_id": "CUST-001",
        "screening_status": "PENDING",
    },
    "reviewed_by": "integration-test",
    "review_timestamp": "2026-08-29T00:00:00Z",
    "reviewer_notes": None,
    "policy_context": [
        {
            "policy_id": "SCREENING-POLICY-001",
            "version": "1.0",
            "section": "Requirements",
            "content": "Screening must be CLEAR before wallet opening.",
        }
    ],
}


class FakeProvider:
    """Simple provider used to test router behavior."""

    def __init__(self, name, outcomes):
        self.name = name
        self.model = f"{name}-integration-model"
        self.outcomes = list(outcomes)
        self.call_count = 0

    def generate(self, ai_input):
        self.call_count += 1

        if not self.outcomes:
            raise AssertionError(
                f"{self.name} received more calls than expected."
            )

        outcome = self.outcomes.pop(0)

        if isinstance(outcome, Exception):
            raise outcome

        return LLMExplanation(
            finding_id=ai_input["finding_id"],
            audit_run_id=ai_input["audit_run_id"],
            ai_explanation=f"Generated by {self.name}.",
            ai_recommendation=f"Recommendation from {self.name}.",
            cited_policy_ids=["SCREENING-POLICY-001"],
            provider_used=self.name,
            model_used=self.model,
        )


def test_router_integration_primary_provider_success():
    """
    Happy path:

        Router -> Groq -> success

    Gemini must not be called.
    """

    groq = FakeProvider("groq", [None])
    gemini = FakeProvider("gemini", [None])

    result = explain(
        SAMPLE_AI_INPUT,
        primary=groq,
        fallback=gemini,
    )

    assert result["finding_id"] == "F-INTEGRATION-001"
    assert result["audit_run_id"] == "RUN-INTEGRATION-001"
    assert result["provider_used"] == "groq"
    assert result["model_used"] == "groq-integration-model"

    assert groq.call_count == 1
    assert gemini.call_count == 0


def test_router_integration_primary_transient_failure_then_success():
    """
    Primary provider fails transiently once.

        Groq -> transient failure
             -> retry Groq
             -> success

    Gemini must not be called.
    """

    groq = FakeProvider(
        "groq",
        [
            LLMTransientError("temporary Groq failure"),
            None,
        ],
    )

    gemini = FakeProvider("gemini", [None])

    result = explain(
        SAMPLE_AI_INPUT,
        primary=groq,
        fallback=gemini,
    )

    assert result["provider_used"] == "groq"
    assert groq.call_count == 2
    assert gemini.call_count == 0


def test_router_integration_fails_over_to_fallback():
    """
    Primary provider fails twice.

        Groq -> failure
             -> retry
             -> failure
             -> Gemini fallback -> success
    """

    groq = FakeProvider(
        "groq",
        [
            LLMTransientError("Groq unavailable"),
            LLMTransientError("Groq still unavailable"),
        ],
    )

    gemini = FakeProvider("gemini", [None])

    result = explain(
        SAMPLE_AI_INPUT,
        primary=groq,
        fallback=gemini,
    )

    assert result["provider_used"] == "gemini"
    assert result["model_used"] == "gemini-integration-model"

    assert groq.call_count == 2
    assert gemini.call_count == 1


def test_router_integration_output_error_retries_primary():
    """
    Malformed provider output is retried on the same provider.

        Groq -> output error
             -> retry Groq
             -> success
    """

    groq = FakeProvider(
        "groq",
        [
            LLMOutputError("malformed JSON"),
            None,
        ],
    )

    gemini = FakeProvider("gemini", [None])

    result = explain(
        SAMPLE_AI_INPUT,
        primary=groq,
        fallback=gemini,
    )

    assert result["provider_used"] == "groq"
    assert groq.call_count == 2
    assert gemini.call_count == 0


def test_router_integration_config_error_does_not_failover():
    """
    Configuration errors are not retryable and must not trigger
    fallback.

        Groq -> configuration error
             -> immediate failure
             -> Gemini NOT called
    """

    groq = FakeProvider(
        "groq",
        [
            LLMConfigError("GROQ_API_KEY is invalid"),
        ],
    )

    gemini = FakeProvider("gemini", [None])

    with pytest.raises(LLMConfigError):
        explain(
            SAMPLE_AI_INPUT,
            primary=groq,
            fallback=gemini,
        )

    assert groq.call_count == 1
    assert gemini.call_count == 0


def test_router_integration_both_providers_fail():
    """
    Both providers fail.

        Groq -> failure
             -> retry
             -> failure
             -> Gemini -> failure
             -> LLMAllProvidersFailedError
    """

    groq = FakeProvider(
        "groq",
        [
            LLMTransientError("Groq failure 1"),
            LLMTransientError("Groq failure 2"),
        ],
    )

    gemini = FakeProvider(
        "gemini",
        [
            LLMTransientError("Gemini failure"),
        ],
    )

    with pytest.raises(LLMAllProvidersFailedError) as exc_info:
        explain(
            SAMPLE_AI_INPUT,
            primary=groq,
            fallback=gemini,
        )

    error = exc_info.value

    assert isinstance(error.primary_error, LLMTransientError)
    assert isinstance(error.fallback_error, LLMTransientError)

    assert groq.call_count == 2
    assert gemini.call_count == 1


def test_router_integration_normalized_output_contract():
    """
    The router must return the same normalized dictionary shape
    regardless of which provider generated the response.
    """

    groq = FakeProvider("groq", [None])
    gemini = FakeProvider("gemini", [None])

    result = explain(
        SAMPLE_AI_INPUT,
        primary=groq,
        fallback=gemini,
    )

    assert set(result.keys()) == {
        "finding_id",
        "audit_run_id",
        "ai_explanation",
        "ai_recommendation",
        "cited_policy_ids",
        "provider_used",
        "model_used",
    }

    assert result["finding_id"] == SAMPLE_AI_INPUT["finding_id"]
    assert result["audit_run_id"] == SAMPLE_AI_INPUT["audit_run_id"]
    assert result["cited_policy_ids"] == ["SCREENING-POLICY-001"]