from engine.audit_pipeline import run_audit


def test_audit_trace_is_created_and_completed():
    result = run_audit()

    assert result.audit_trace is not None

    assert result.audit_trace.audit_run_id

    assert result.audit_trace.completed_at is not None

    assert result.audit_trace.total_records_evaluated > 0

    assert (
        result.audit_trace.total_findings_generated
        == len(result.generated_findings)
    )


def test_audit_trace_contains_expected_controls():
    result = run_audit()

    assert set(result.audit_trace.controls_executed) == {
        "SCREENING_001",
        "RISK_001",
        "ARABIC_NAME_001",
        "DORMANT_001",
        "RECON_001",
    }


def test_audit_trace_finding_count_matches_generated_findings():
    result = run_audit()

    assert (
        result.audit_trace.total_findings_generated
        == len(result.generated_findings)
    )


def test_findings_wait_for_human_review_before_explanation():
    """
    Findings generated by the deterministic audit stage must
    remain in REVIEW status and must not receive explanations
    before human confirmation.
    """

    result = run_audit()

    assert len(result.generated_findings) == 223

    # Every finding must still be waiting for human review.
    assert all(
        finding["finding_status"] == "REVIEW"
        for finding in result.generated_findings
    )

    # No explanation is allowed before human confirmation.
    assert result.explanations == []


def test_explanations_match_generated_findings():
    """
    Pre-AI stage intentionally produces no explanations.

    Explanation generation happens only after a finding
    has been CONFIRMED by a human reviewer.
    """

    result = run_audit()

    # No explanations exist at this stage.
    assert result.explanations == []

    # Generated findings remain traceable.
    findings_by_id = {
        finding["finding_id"]: finding
        for finding in result.generated_findings
    }

    assert len(findings_by_id) == 223

    for finding in result.generated_findings:

        assert finding["finding_id"] in findings_by_id

        assert finding["audit_run_id"] == (
            result.audit_trace.audit_run_id
        )

        assert finding["finding_status"] == "REVIEW"


def test_audit_trace_preserves_audit_run_identity():
    """
    Every generated finding must belong to the same audit run
    represented by the audit trace.
    """

    result = run_audit()

    audit_run_id = result.audit_trace.audit_run_id

    assert audit_run_id

    for finding in result.generated_findings:

        assert finding["audit_run_id"] == audit_run_id